3 mains to deliver error:
1. throw error
2. pass the error to cb
3. emit error event

error: instance of the Error class. When you throw an error, it becomes an exception.
Or:
callback(new Error('something bad happened'));

=> the only common case for try/catch is JSON.parse and other validation function => very UNCOMMON to catch error from synchrounous
function

1.throw delivers error synchronously
2.cb to deliver event asynchly => callback(err, result) => only one of err and result is non-null
3.emit error: 
  ops that may produce multiple errors or multiple results
  objects represent complex state machines

operational error in async funciton

operational error in sync funtion

Inside a function, if any op error can be delivered asynch, then all op errors need delivered asynch => i.e., either all sync or all async

